import { build } from 'esbuild';
import { mkdir, copyFile, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const output = new URL('../../vendor/youtube-home/', import.meta.url);
await mkdir(output, { recursive: true });
await build({
    entryPoints: [fileURLToPath(new URL('./page.mjs', import.meta.url))],
    outfile: fileURLToPath(new URL('page.js', output)),
    bundle: true, format: 'iife', platform: 'browser', target: 'chrome142',
    minify: true, keepNames: true, legalComments: 'eof',
    banner: { js: '/* Generated by integrations/youtube-home/build.mjs. YouTube.js 18.0.0 (MIT). */' },
});
await copyFile(new URL('./node_modules/youtubei.js/LICENSE', import.meta.url), new URL('LICENSE.youtubei.js', output));
await copyFile(new URL('./node_modules/fflate/LICENSE', import.meta.url), new URL('LICENSE.fflate', output));
await copyFile(new URL('./node_modules/meriyah/LICENSE.md', import.meta.url), new URL('LICENSE.meriyah', output));
// This published dependency omits its root LICENSE file. Keep the Apache license
// from its tagged upstream repository alongside its embedded BSD attribution.
const varint = await readFile(new URL('./node_modules/@bufbuild/protobuf/dist/esm/wire/varint.js', import.meta.url), 'utf8');
await writeFile(new URL('LICENSE.protobuf-bsd', output), varint.split('\n\n')[0].replace(/^\/\/ ?/gm, '') + '\n');
